### ISSUE TITLE
JSTOR as monopoly? 

### ISSUE THREAD

**Issue by amandafrench** [ekansa-pubs/ekansa-pubs.github.io#23]
Really interesting article, @ekansa -- still digesting it. I think you're very right that the scale of JSTOR makes it almost indispensable for much scholarship, and I think you're right too that it would be difficult to fund another JSTOR, an alternative JSTOR (though maybe Mellon would! talk about a lock-in on the venture capital part of humanities scholarship). But I'm not sure if JSTOR is exactly a monopoly, though it might be. I'm just thinking here of the mundane fact that most publishers license their journal content to several different largeish vendors, so that any individual article found in JSTOR might also be available elsewhere. And "elsewhere" means in databases run by for-profit companies whose products (I think) cost more than JSTOR if measured on a per-article basis. 

Now I'm not certain of this, and have only done the most cursory of searches through LIS literature (using "JSTOR" as a keyword suuuucks, because you get articles in rather than about it). Unscientific sample point of one: I search Google Scholar for the journal title "Near Eastern Archaeology" and come up with an article titled "Satellite images and Near Eastern landscapes" from 2001 by Nicholas Kouchoukos. Through Virginia Tech library subscriptions, I can read that article in JSTOR, yes, but I can also get it through ProQuest or on some French site called RefDoc. 

If you want to talk information oligarchies, man, read about ProQuest: http://newsbreaks.infotoday.com/NewsBreaks/ProQuest-to-Acquire-Ex-Libris-Group-106901.asp 

So, again, I haven't yet found out how much content is _only_ available through JSTOR -- could be that it's most of it. Will ask my LIS friend if they know. But from a library point of view, JSTOR tends to look like the good guy: they are a nonprofit, they give cheap access to developing nations, they provide flexible subscriptions instead of making you buy "big deal" bundles (like cable!) of a whole bunch of stuff you don't want, and they let researchers have analytic access to their data corpus through their research program. 

Here endeth my thoughts about JSTOR as monopoly.

**Comment by ekansa** [comment]
Wow! Thanks for the comment and discussion about JSTOR + ProQuest. I agree, and don't mean to imply JSTOR is "evil".There are definitely far worse players in the landscape. But the reason I focused on JSTOR centers on how it is a nonprofit, started with grants, and has been highlighted as the example of doing things right.

So I'm going to think about how to better situate this discussion given your feedback and notes about ProQuest. Thanks!

**Comment by ekansa** [comment]
Yes about JSTOR being a terrible keyword to throw at Google! I've done some more work to clarify that JSTOR is not a villain in this space and have noted your comment in my paper. It's in the offline version I'm submitting for formatting reasons and I hope to update the Github version shortly..

THANKS!!
-E
