### ISSUE TITLE
A Few Comments on "Click Here"

### ISSUE THREAD

**Issue by d-riedel** [ekansa-pubs/ekansa-pubs.github.io#26]
Enjoyed it very much @ekansa  Here are my comments:

I suspect that archeologists know what the AAI is, but the non-initiated like me would not mind to learn what is behind the acronym: American Archeology I??

Early on you underline that Open Context operates with a much lower overhead 
https://en.wikipedia.org/wiki/Overhead
https://en.wikipedia.org/wiki/Overhead_%28business%29
https://en.wikipedia.org/wiki/Labor_burden
than large research institutions.  While I understand your pride, I wonder whether it is an entirely fair or wise comparison -- taking the long view.  For the last decades, research institutions were de facto forced to transform themselves into corporate organizations -- in accordance with the belief that free markets are the best model for (almost) every human activity -- and thus they had to adopt corporate accounting models.  I for one find it very counter-intuitive that non-profit research institutions can generate any form of overhead at all, as it assumes that everything and every act associated with teaching and research can be quantified, and thus be monetized, in accordance with the fee-for-service model.  Moreover, I wish I knew an economist cum accountant who could tell me whether in research institutions overhead is imploding because tenured positions, which would be considered payroll expenses, are in decline.  At the same time, fundraising expenses are also considered overhead...

It seems to me that in different fields the term alt-ac is very differently used.  For example, the American Historical Association (AHA) considers everyone who is not a college or university teacher of any rank and title an alt-ac, so that their alt-acs are, for example, academic librarians or administrators, as well as every person with a PhD working in the for-profit world.  In other words, for the AHA the distinction between ac and alt-ac is not the difference between (possible) tenured employment and short-time soft money (that is: the much maligned gravy train).  The AHA at least considers non-tenure track research faculty and adjuncts acs, however lousy and insecure their lives may be...

Like @amandafrench I am a bit surprised by your JSTOR example.  I know from German academic librarians that they do not subscribe to JSTOR because within the EU's funding maze for the Humanities they get much of what is available via JSTOR via EU depositories which are cheaper or Open-Access, e.g. Gallica.  

Thinking back about your essay, I wonder whether one of the fundamental underlying issues is that for the last 30 years or so most western capitalist societies have abandoned their commitment to state-funding of culture, education and all research that is not driven by immediate applicability in any commercial, for-profit context.  It seems to me that explorations of "open access" rarely address the white elephant in the room: As long as in a reflexively rather anti-intellectual environment it is deemed unfair that _all_ citizens via federal, state and local budgets fund culture, education and research as ends in themselves, commercial models and private donors will de facto determine how funding is made available for research, the preservation of research outcomes (e.g., archeological field reports), and Open-Access to the research outcomes.  Against this background, it seems only fitting that I am now using GitHub
https://github.com/about
to comment on your essay. 

PS -- One of my current pet ideas -- which I have, of course unsuccessfully, pitched to Columbia's Data Science Institute
http://datascience.columbia.edu/columbia-data-science
earlier this year -- is a conference exploring abandoned and never realized data science research projects at any state of their development: "What If: A Contrafactual History of Data Science."  Aside from rejected proposals, what about projects that remain pet projects because we figure that politically, as well as structurally, it will be impossible to obtain funding for them?  For example: there is -- according to my knowledge -- currently no way of obtaining funding via CLIR etc. for recataloging insufficiently cataloged rare library holdings (e.g., rare books in non-western languages): once such a book has a MARC record which will be added to OCLC, however faulty, the book is considered cataloged, and any correction, even of obvious mistakes, depends on individual generosity, lots of nerve, and deep institutional knowledge.

**Comment by ekansa** [comment]
A very belated but deeply felt thanks for your feedback! 

I've been completely consumed with, appropriately enough, grant writing and fund raising. These processes have their own immovable time tables and I think got in the way of discussion about this paper. 

Thanks for the points about the varied definitions of Alt-Ac and your feedback about my discussion of  JSTOR. I'm working on on refining that part of the paper, so it makes similar points without making JSTOR  seem like a villain...
